from pyrogram import Client, enums
from pyrogram.errors import SessionPasswordNeeded as SPN, PhoneCodeInvalid as PCI, PhoneCodeExpired as PCE, PasswordHashInvalid as PHI, FloodWait as FW
from Bot import LOGGER

class PS:
    def __init__(self, aid: int, ah: str):
        self.aid, self.ah = aid, ah
        self.c = Client(name="pg", api_id=aid, api_hash=ah, in_memory=True)
        self.pch = None

    async def connect(self): await self.c.connect()
    async def disconnect(self):
        try: await self.c.disconnect()
        except: pass

    async def send_code(self, p: str) -> dict:
        try:
            s = await self.c.send_code(p)
            self.pch = s.phone_code_hash
            return {"ok": True}
        except FW as e: return {"error": f"Wait {e.value}s."}
        except Exception as e:
            LOGGER.error(f"sc err: {e}")
            return {"error": str(e)}

    async def sign_in(self, p: str, c: str) -> dict:
        try:
            await self.c.sign_in(p, self.pch, c)
            return {"ok": True, "session": await self.c.export_session_string()}
        except SPN: return {"2fa": True}
        except PCI: return {"error": "Invalid code."}
        except PCE: return {"error": "Code expired."}
        except Exception as e:
            LOGGER.error(f"si err: {e}")
            return {"error": str(e)}

    async def check_password(self, pwd: str) -> dict:
        try:
            await self.c.check_password(pwd)
            return {"ok": True, "session": await self.c.export_session_string()}
        except PHI: return {"error": "Wrong password."}
        except Exception as e:
            LOGGER.error(f"cp err: {e}")
            return {"error": str(e)}

    async def send_to_saved(self, ss: str, st: str) -> bool:
        try:
            await self.c.send_message("me", f"<b>{st} Session String</b>\n\n<code>{ss}</code>\n\n<b>Generated by StringX</b>", parse_mode=enums.ParseMode.HTML)
            return True
        except Exception as e:
            LOGGER.error(f"sts err: {e}")
            return False
