from telethon import TelegramClient as TC
from telethon.sessions import StringSession as SS
from telethon.errors import SessionPasswordNeededError as SPN, PhoneCodeInvalidError as PCI, PhoneCodeExpiredError as PCE, PasswordHashInvalidError as PHI, FloodWaitError as FW
from Bot import LOGGER

class TS:
    def __init__(self, aid: int, ah: str):
        self.aid, self.ah = aid, ah
        self.c = TC(SS(), aid, ah)
        self.pch = None

    async def connect(self): await self.c.connect()
    async def disconnect(self):
        try: await self.c.disconnect()
        except: pass

    async def send_code(self, p: str) -> dict:
        try:
            s = await self.c.send_code_request(p)
            self.pch = s.phone_code_hash
            return {"ok": True}
        except FW as e: return {"error": f"Wait {e.seconds}s."}
        except Exception as e:
            LOGGER.error(f"sc err: {e}")
            return {"error": str(e)}

    async def sign_in(self, p: str, c: str) -> dict:
        try:
            await self.c.sign_in(p, c, phone_code_hash=self.pch)
            return {"ok": True, "session": self.c.session.save()}
        except SPN: return {"2fa": True}
        except PCI: return {"error": "Invalid code."}
        except PCE: return {"error": "Code expired."}
        except Exception as e:
            LOGGER.error(f"si err: {e}")
            return {"error": str(e)}

    async def check_password(self, pwd: str) -> dict:
        try:
            await self.c.sign_in(password=pwd)
            return {"ok": True, "session": self.c.session.save()}
        except PHI: return {"error": "Wrong password."}
        except Exception as e:
            LOGGER.error(f"cp err: {e}")
            return {"error": str(e)}

    async def send_to_saved(self, ss: str, st: str) -> bool:
        try:
            await self.c.send_message("me", f"**{st} Session String**\n\n`{ss}`\n\n**Generated by StringX**")
            return True
        except Exception as e:
            LOGGER.error(f"sts err: {e}")
            return False
